# Generated by Django 4.2.13 on 2024-05-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.DecimalField(db_comment='Quantidade disponível', decimal_places=5, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='receitaingrediente',
            name='quantidade',
            field=models.DecimalField(db_comment='quantidade usada na receita por unidade de medida', decimal_places=5, max_digits=11),
        ),
    ]
