# Generated by Django 4.2.13 on 2024-05-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_produto_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preco',
            name='data_cotacao',
            field=models.DateField(db_comment='Data Cotação'),
        ),
    ]
