# Generated by Django 4.2.13 on 2024-06-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_aula_options_alter_disciplina_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemnotafiscal',
            old_name='preco_nitario',
            new_name='preco_unitario',
        ),
        migrations.AlterField(
            model_name='movimento',
            name='tipo',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída'), ('A', 'Ajuste de auditoria'), ('D', 'Devolução')], db_comment='Tipo do movimento', max_length=1),
        ),
    ]
